# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
{
  "@apollo/protobufjs@npm:1.2.6" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-bHEo10lTb+e+WF/5zrbKeSiuLAJmJ0J6YTC724wU58pGznJYyxoZKwW/QAQ2ltexxIH7n5RRXYqDhz50CNQ/Yg==";
    };
  };
  "@babel/core@npm:7.19.6" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "@babel/parser@npm:7.19.6" = {
    dependencies = {
      "@babel/types" = "@babel/types@npm:7.19.4";
    };
  };
  "@babel/parser@npm:7.20.2" = {
    dependencies = {
      "@babel/types" = "@babel/types@npm:7.19.4";
    };
  };
  "@babel/traverse@npm:7.19.6" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "@babel/traverse@npm:7.20.1" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "@esbuild/android-arm@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@esbuild/linux-loong64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@mapbox/node-pre-gyp@npm:1.0.10" = {
    dependencies = {
      "node-fetch" = "node-fetch@npm:2.6.7";
    };
  };
  "@next/swc-android-arm-eabi@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-android-arm64@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-darwin-arm64@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-4xsDS4PrKPG3+qZC1clxo6bpG69DxeHt7FG34kOwQVDtZUZwp/W8UdBWz3FOTzbNiIyF7OBv+KETYb1MU+Umug==";
    };
  };
  "@next/swc-darwin-x64@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-freebsd-x64@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-linux-arm-gnueabihf@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-linux-arm64-gnu@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-linux-arm64-musl@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-linux-x64-gnu@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "x86_64-linux" = "sha512-4yXKf3VLGHtR4xsNYbqpxGAmthsENlwX8eZjXHd5PxADNws8MwkdcwLspDxifrAdcuO68WVM3UiTNUuZN/Vt0A==";
    };
  };
  "@next/swc-linux-x64-musl@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-win32-arm64-msvc@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-win32-ia32-msvc@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "@next/swc-win32-x64-msvc@npm:12.3.1" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "agent-base@npm:6.0.2" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "agentkeepalive@npm:4.2.1" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "apollo-env@npm:0.6.6" = {
    dependencies = {
      "node-fetch" = "node-fetch@npm:2.6.7";
    };
  };
  "apollo-env@npm:0.9.2" = {
    dependencies = {
      "node-fetch" = "node-fetch@npm:2.6.7";
    };
  };
  "apollo-server-env@npm:3.2.0" = {
    dependencies = {
      "node-fetch" = "node-fetch@npm:2.6.7";
    };
  };
  "canvas@npm:2.10.1" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-mM5kVat75TLZDEGd4PQ23PsBq2mWSXGzCt8xaBmvyBBMlSWZI0iUAfXMXwRsMUPpOKLo27nDsoSjpEF+/ZlgNA==";
      "x86_64-linux" = "sha512-Y1CKmGQparqpkDOU54UV2Jq9xGJU8v+Y/wyh1F1YkZiYgeEvC2KMiA74kXvcHsoT0ynXHIwe2dS1ZD0RyyNwsw==";
    };
  };
  "core-js@npm:3.26.0" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-0xpUcVhsgitoHrvU7350NHr8izKoxK3YL+YoiDKg2dNk9SqUCmockyjYoDahsT1n3H0/tgok7JWsoCHLL7Phgg==";
    };
  };
  "esbuild-android-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-android-arm64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-darwin-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-darwin-arm64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-Y5+ADVjp0WbzDUXRVintz+Tk0Wf3aUCzQvA1zWSxGlOrsttAkAJdt069ERiFN3EmICIu74R566OiplD6bRl/fA==";
    };
  };
  "esbuild-freebsd-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-freebsd-arm64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-32@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "x86_64-linux" = "sha512-H6P3xJuvxQ6JN1xAWDjZGRlHCgBju4iJZlvlhrUnDsqD1ZLZhd7gKYuN+ALWIRW+zxVqYAN9rLTKKZE5SECjXg==";
    };
  };
  "esbuild-linux-arm@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-arm64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-mips64le@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-ppc64le@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-riscv64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-linux-s390x@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-netbsd-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-openbsd-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-sunos-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-windows-32@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-windows-64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild-windows-arm64@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHash = "";
  };
  "esbuild@npm:0.15.10" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-1vaO639lFTNMppXf76TOY6NEbmVUkAiCNlYM/f3Q7Plf1TIGnyKgfHK7YiCwS8wtLYzzvrEp2JyIewZfhlu2xw==";
      "x86_64-linux" = "sha512-1vaO639lFTNMppXf76TOY6NEbmVUkAiCNlYM/f3Q7Plf1TIGnyKgfHK7YiCwS8wtLYzzvrEp2JyIewZfhlu2xw==";
    };
  };
  "fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>::version=2.3.2&hash=18f3a7" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-uka9eemEm6sAGeKXHGrM/cfX65Rd2RWVeApfmeZrgeCG7giNVo2HDHPIev7RIMz07ObyqlBN+EdFaJ8Q9JsnQA==";
    };
  };
  "http-proxy-agent@npm:5.0.0" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "https-proxy-agent@npm:5.0.1" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "istanbul-lib-source-maps@npm:4.0.1" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "jest-haste-map@npm:29.2.1" = {
    dependencies = {
      "fsevents" = "fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>::version=2.3.2&hash=18f3a7";
    };
  };
  "jest-resolve@npm:29.2.2" = {
    dependencies = {
      "resolve" = "resolve@patch:resolve@npm%3A1.22.1#optional!builtin<compat/resolve>::version=1.22.1&hash=07638b";
    };
  };
  "nan@npm:2.17.0" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-vaHklwbCugGO1eXXYwW7TmwZUx06adQReESZw4KTdbNPoP0ioUIBnAjBWaWPrhxQEE/czsGxJh504Ce/+/dHyA==";
      "x86_64-linux" = "sha512-vaHklwbCugGO1eXXYwW7TmwZUx06adQReESZw4KTdbNPoP0ioUIBnAjBWaWPrhxQEE/czsGxJh504Ce/+/dHyA==";
    };
  };
  "node-addon-api@npm:5.0.0" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-Uw8BXOHMOmRcUkY4xfrITrenvBWpuTVhA33ECB4RkI8R1USvopS9t8XRjrqUKtlQ2L9qoa5KzBbTpWtJDnQwUg==";
      "x86_64-linux" = "sha512-Uw8BXOHMOmRcUkY4xfrITrenvBWpuTVhA33ECB4RkI8R1USvopS9t8XRjrqUKtlQ2L9qoa5KzBbTpWtJDnQwUg==";
    };
  };
  "node-gyp@npm:9.3.0" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-3Ct9L1Ijy3qX2zq3Rf+lGjHMbrK8SUa2jQCdWB8RCo4pktb97WJ1JkxhJdC7tPSLlgQ2htJIH8wyKCB6bgMR6g==";
      "x86_64-linux" = "sha512-3Ct9L1Ijy3qX2zq3Rf+lGjHMbrK8SUa2jQCdWB8RCo4pktb97WJ1JkxhJdC7tPSLlgQ2htJIH8wyKCB6bgMR6g==";
    };
  };
  "open@patch:open@npm%3A8.4.0#.yarn/patches/open-npm-8.4.0-df63cfe537::version=8.4.0&hash=e6ee73&locator=root-workspace-0b6124%40workspace%3A." = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-fhLJ778B2/lZjzfKYzt1dFk4OzenM2MFEiGhy4a4fjVJM7OLL4YzBLWaS64NUtWcWa+5ULvlSOyA9KliBgPa3A==";
      "x86_64-linux" = "sha512-fhLJ778B2/lZjzfKYzt1dFk4OzenM2MFEiGhy4a4fjVJM7OLL4YzBLWaS64NUtWcWa+5ULvlSOyA9KliBgPa3A==";
    };
  };
  "rechoir@npm:0.7.1" = {
    dependencies = {
      "resolve" = "resolve@patch:resolve@npm%3A1.22.1#optional!builtin<compat/resolve>::version=1.22.1&hash=07638b";
    };
  };
  "rechoir@npm:0.8.0" = {
    dependencies = {
      "resolve" = "resolve@patch:resolve@npm%3A1.22.1#optional!builtin<compat/resolve>::version=1.22.1&hash=07638b";
    };
  };
  "sharp@npm:0.31.1" = {
    shouldBeUnplugged = true;
    outputHashByPlatform = {
      "aarch64-darwin" = "sha512-5DMQOkRDmf0tbAgvGSEikgINATLcRm8WKkaLyp1XOurtG0LIMJUlz8mB5E2cNpFuigLIrr7LrK+mtaUL/QSxkQ==";
      "x86_64-linux" = "sha512-jirTC3XTIyBYEe1l9IgSr8S4zkkl6YvRNaqeQk1itXmbibRfk0KxziApSAmNByf+y0Z9vmMPmnJpr6OE3PODOg==";
    };
  };
  "socks-proxy-agent@npm:7.0.0" = {
    dependencies = {
      "debug" = "debug@npm:4.3.4";
    };
  };
  "styled-components@npm:5.1.0" = {
    dependencies = {
      "react-is" = "react-is@npm:18.2.0";
    };
  };
  "testa@workspace:packages/testa" = {
    dependencies = {
      "rimraf" = "rimraf@portal:./localPackageTests/test-portal::locator=root-workspace-0b6124%40workspace%3A.";
      "typescript" = "typescript@patch:typescript@npm%3A4.8.4#optional!builtin<compat/typescript>::version=4.8.4&hash=701156";
    };
  };
  "testb@workspace:packages/testb" = {
    dependencies = {
      "fsevents" = "fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>::version=2.3.2&hash=18f3a7";
      "open" = "open@patch:open@npm%3A8.4.0#.yarn/patches/open-npm-8.4.0-df63cfe537::version=8.4.0&hash=e6ee73&locator=root-workspace-0b6124%40workspace%3A.";
      "knex" = "knex@npm:2.3.0";
    };
  };
}
